# Generated by Django 4.2.1 on 2023-05-13 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elites", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="members",
            name="country",
            field=models.CharField(default="empty", max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="members",
            name="fav_player",
            field=models.CharField(default="empty", max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="members",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
